### ISSUE TITLE
Theme Editor (Builder)

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2905]
Allow users to easily customize the look and feel for surveys.

- [x] Property Grid
  - [x] survey
  - [x] section
  - [x] New editors
    - [x] surveyjs/survey-creator#3942
    - [x] surveyjs/survey-creator#3943
    - [x] surveyjs/survey-creator#3944
- [x] surveyjs/survey-creator#4026
- [x] surveyjs/survey-library#6063
- [x] extract to tab
- [x] #4126
- [x] #4153
- [x] colors are not applied to popups https://github.com/surveyjs/survey-library/issues/6289
- [x] Theme
  - [x] apply css variable from theme
  - [x] implement 10 light themes
  - [x] implement 10 dark themes
  - [x] save/export result

**Comment by JaneGaid** [comment]
+1 request

**Comment by JaneSjs** [comment]
+1
[T11777 -  How to change the  color, font and background color of the survey ? While creating survey there is no option](https://surveyjs.answerdesk.io/internal/ticket/details/T11777)

we want to have background image on the survey body and other options like different font style

**Comment by JaneSjs** [comment]
What customers asked:
- Build a theme from scratch

**Comment by mikeamelin** [comment]
Property Grid
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=15685%3A138785

Short Description 
https://github.com/surveyjs/private-tasks/issues/60

**Comment by JaneSjs** [comment]
+1 T12456 - Surveyjs creator. Create new theme. React
https://surveyjs.answerdesk.io/internal/ticket/details/T12456

**Comment by tsv2013** [comment]
https://www.figma.com/file/7QOeoDDCaPuqzWAROR0kDY/Creator?node-id=15685-138785&t=Vg6ZzxB2DvJMKFYC-0

**Comment by OlgaLarina** [comment]
https://github.com/surveyjs/survey-creator/pull/4168
