### ISSUE TITLE
[GROUP] Toolbox enchancements

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#4477]
- [ ] ~Updated categories for the toolbox [#1040](https://github.com/surveyjs/service/issues/1040)~
- [x] Scroll bar for the Toolbox [#1039](https://github.com/surveyjs/service/issues/1039)
- [ ] Toolbox Categories - Add an option to render image actions in a category and item caption area #4364
- [x] Toolbox - Disable a toolbox item #3520
- [x] Toolbox - Add search option for toolbox items (suppose if the elements in toolbox is more than 100 and need to search how do we acheive) #2231
- [x] Add an option to display a tooltip when hovering over a toolbox item's label/caption: https://surveyjs.answerdesk.io/internal/ticket/details/T14351
